#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# Install local packtools in editable mode (dev only - uses bind-mounted workspace)
# pip install -e /packtools --quiet

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
