[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
pythonpath = .
addopts = --reuse-db
filterwarnings =
    ignore:pkg_resources is deprecated as an API:UserWarning:packtools.catalogs
    ignore:Deprecated call to `pkg_resources.declare_namespace\('google'\)`:DeprecationWarning:pkg_resources
