# Generated by Django 6.0.5 on 2026-06-09 00:35

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=50, unique=True, verbose_name='Resource')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last updated at')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Last success at')),
            ],
            options={
                'verbose_name': 'Core sync state',
                'verbose_name_plural': 'Core sync states',
            },
        ),
        migrations.CreateModel(
            name='FlexibleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Month')),
                ('day', models.IntegerField(blank=True, null=True, verbose_name='Day')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Language Name')),
                ('code2', models.TextField(blank=True, null=True, verbose_name='Language code 2')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('license_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='LicenseStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('license_p', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
