# Generated by Django 6.0.5 on 2026-06-09 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journals', '0002_initial'),
        ('manuscripts', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journals.issue'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journals.journal'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='articleartifact',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='manuscripts.article'),
        ),
        migrations.AddField(
            model_name='articleartifact',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='articleartifact',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='articlereference',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='articlereference',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_references', to='references.reference'),
        ),
        migrations.AddField(
            model_name='articlereference',
            name='selected_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_references', to='references.elementcitation'),
        ),
        migrations.AddField(
            model_name='articlereference',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='articlestructureversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_versions', to='manuscripts.article'),
        ),
        migrations.AddField(
            model_name='articlestructureversion',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='articlestructureversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='articlereference',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='manuscripts.articlestructureversion'),
        ),
        migrations.AddField(
            model_name='articleartifact',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='manuscripts.articlestructureversion'),
        ),
        migrations.AddField(
            model_name='citationoccurrence',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='citationoccurrence',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='citations', to='manuscripts.articlereference'),
        ),
        migrations.AddField(
            model_name='citationoccurrence',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='manuscripts.articlestructureversion'),
        ),
        migrations.AddField(
            model_name='citationoccurrence',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='processing',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='processings', to='manuscripts.article'),
        ),
        migrations.AddField(
            model_name='processing',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='processing',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='articlestructureversion',
            name='processing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_versions', to='manuscripts.processing'),
        ),
        migrations.AddField(
            model_name='articleartifact',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='manuscripts.processing'),
        ),
        migrations.CreateModel(
            name='ArticleInput',
            fields=[
            ],
            options={
                'verbose_name': 'DOCX',
                'verbose_name_plural': 'DOCX',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manuscripts.processing',),
        ),
        migrations.CreateModel(
            name='SPSPackageImport',
            fields=[
            ],
            options={
                'verbose_name': 'SPS Package',
                'verbose_name_plural': 'SPS Packages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manuscripts.processing',),
        ),
        migrations.CreateModel(
            name='XMLImport',
            fields=[
            ],
            options={
                'verbose_name': 'XML',
                'verbose_name_plural': 'XML',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manuscripts.processing',),
        ),
        migrations.AddField(
            model_name='processingevent',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='manuscripts.article'),
        ),
        migrations.AddField(
            model_name='processingevent',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='processingevent',
            name='processing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='manuscripts.processing'),
        ),
        migrations.AddField(
            model_name='processingevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddConstraint(
            model_name='articlereference',
            constraint=models.UniqueConstraint(fields=('structure', 'ref_id'), name='unique_structure_ref_id'),
        ),
        migrations.AddConstraint(
            model_name='articlereference',
            constraint=models.UniqueConstraint(fields=('structure', 'position'), name='unique_structure_ref_position'),
        ),
        migrations.AddConstraint(
            model_name='articlestructureversion',
            constraint=models.UniqueConstraint(fields=('article', 'version'), name='unique_article_structure_version'),
        ),
        migrations.AddIndex(
            model_name='articleartifact',
            index=models.Index(fields=['processing', 'article', 'artifact_type', 'is_current'], name='manuscripts_process_8a07b8_idx'),
        ),
        migrations.AddIndex(
            model_name='processingevent',
            index=models.Index(fields=['processing', 'article', 'action', 'status'], name='manuscripts_process_38c798_idx'),
        ),
    ]
