# Generated by Django 6.0.5 on 2026-07-02 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeminiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gemini model",
                "verbose_name_plural": "Gemini models",
            },
        ),
        migrations.CreateModel(
            name="HuggingFaceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "name_model",
                    models.CharField(
                        help_text="e.g. bartowski/Llama-3.2-3B-Instruct-GGUF",
                        max_length=255,
                        verbose_name="Model name",
                    ),
                ),
                (
                    "name_file",
                    models.CharField(
                        help_text="e.g. Llama-3.2-3B-Instruct-Q4_K_M.gguf",
                        max_length=255,
                        verbose_name="Model file",
                    ),
                ),
                (
                    "hf_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="HuggingFace token"
                    ),
                ),
                (
                    "download_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No model"),
                            (2, "Downloading"),
                            (3, "Downloaded"),
                            (4, "Download error"),
                        ],
                        default=1,
                        verbose_name="Download status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "HuggingFace model",
                "verbose_name_plural": "HuggingFace models",
            },
        ),
        migrations.CreateModel(
            name="OllamaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="e.g. http://host:11434", verbose_name="Ollama URL"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Select after fetching",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
                (
                    "is_vision",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to use vision pipeline (page images). When disabled, text pipeline is used.",
                        verbose_name="Vision model",
                    ),
                ),
                (
                    "docx_extractor",
                    models.CharField(
                        choices=[
                            ("zipfile", "Zipfile (built-in)"),
                            ("docling", "Docling (OCR-capable, requires pytorch)"),
                        ],
                        default="zipfile",
                        help_text="Method to extract plain text from DOCX for LLM prompts.",
                        max_length=16,
                        verbose_name="DOCX text extractor",
                    ),
                ),
                (
                    "context_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max input tokens for this model. Leave empty for auto-detect via API.",
                        null=True,
                        verbose_name="Context tokens",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ollama model",
                "verbose_name_plural": "Ollama models",
            },
        ),
    ]
