# Generated by Django 6.0.5 on 2026-06-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('volume', models.CharField(blank=True, max_length=20, verbose_name='Volume')),
                ('season', models.CharField(blank=True, max_length=20, verbose_name='Season')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Year')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='Month')),
                ('supplement', models.CharField(blank=True, max_length=20, verbose_name='Supplement')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-year', 'journal', 'volume', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True, verbose_name='Title')),
                ('short_title', models.TextField(blank=True, verbose_name='Short title')),
                ('title_nlm', models.TextField(blank=True, verbose_name='NLM title')),
                ('acronym', models.CharField(blank=True, max_length=50, verbose_name='Acronym')),
                ('issn', models.CharField(blank=True, max_length=32, verbose_name='SciELO ISSN')),
                ('pissn', models.CharField(blank=True, max_length=32, verbose_name='Print ISSN')),
                ('eissn', models.CharField(blank=True, max_length=32, verbose_name='Electronic ISSN')),
                ('publisher_name', models.TextField(blank=True, verbose_name='Publisher name')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['title'],
            },
        ),
    ]
